### ISSUE TITLE
Vulnerability found 

### ISSUE THREAD

**Issue by jamaljeantobias** [coinables/orion#2]
I hope this message finds you well. I’ve identified a potential security vulnerability in your project that I would like to bring to your attention. However, to prevent any public disclosure, I’d prefer to share the details privately.

Could you please provide me with the appropriate contact information or a secure method to report the issue?

Thank you for your time and for maintaining this project

**Comment by coinables** [comment]
Hi Jamal, feel free to post. This is a client-side serverless web app.
There's very little consequence to the project and/or others.
